### ISSUE TITLE
Please consider adding your PGP key to OpenTofu

### ISSUE THREAD

**Issue by franklouwers** [alekc/terraform-provider-kubectl#101]
Hi Alekc,

First up, thanks for the kubectl terraform provider!

Could you please have a look at https://github.com/opentofu/registry/blob/main/CONTRIBUTING.md and submit your PGP key to the OpenTofu registry at https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+?

Your provider works out of the box with OpenTofu, but it can't verify the signature. Submitting your key would improve security.

Thanks!

**Comment by alekc** [comment]
Thanks for the heads up. Will do

**Comment by alekc** [comment]
https://github.com/opentofu/registry/pull/326
