### ISSUE TITLE
[Repeating the theme] Use a kubeconfig that hasn't been created yet?

### ISSUE THREAD

**Issue by InfernoFeniks** [alekc/terraform-provider-kubectl#132]
https://github.com/alekc/terraform-provider-kubectl/issues/18#issuecomment-2083878348 
> > ```terraform
> > provider "kubectl" {
> >   config_path      = module.cluster.kubeconfig_path
> >   config_context   = "kind-${kind_cluster.default.name}"
> >   load_config_file = true
> > }
> > ```
> > 
> > 
> >That should provide implicit dependency (similar like it happens with data resource token with eks)
> 
>I tried it. It didn't help. The provider uses an outdated version of the file

**Comment by alekc** [comment]
Please continue the discussion in the original issue instead of opening a new one in this way.
