### ISSUE TITLE
Release `2.1.0`

### ISSUE THREAD

**Issue by stevehipwell** [alekc/terraform-provider-kubectl#177]
I'd like the code changes currently available in the beta releases to be made GA.

**Comment by alekc** [comment]
Apologies, this has been long overdue. I've launched release pipeline https://github.com/alekc/terraform-provider-kubectl/actions/runs/11257314955

**Comment by alekc** [comment]
Marvelous... Goreleaser has a bug where it sorts tag for a release by AZ and it was selecting a wrong tag, so no release... Shifted 2.1.0 tag to a newer commit. 

Fingers crossed it will come through

**Comment by alekc** [comment]
And its public
