### ISSUE TITLE
@Kartoshnikov hang on. I think I got the issue.

### ISSUE THREAD

**Issue by ox0** [alekc/terraform-provider-kubectl#183]
@Kartoshnikov hang on. I think I got the issue. 

Correct me if I am wrong. 

- You have existing infra/objects which have been created by the `gavinbunney/kubectl`. 
- You have changed provider definition from `gavinbunney/kubectl` to `alekc/kubectl` and run plan/apply where you begin to get the error. 

If the above is correct, then this is whats happening. You are running a plan phase where old objects are still linked to gavinbunney/kubectl provider, but at this point of time, there is no configuration for that provider (the fact that there is alekc/kubectl is irrelevant), so terraform applies default config (localhost) and fails as consequence without even trying to execute exec-log. 

Correct procedure is 

- make a backup of your state file 
- as written in https://github.com/alekc/terraform-provider-kubectl?tab=readme-ov-file#changing-providers-for-existing-resources, perform a `terraform state replace-provider gavinbunney/kubectl alekc/kubectl` command
- run terraform init -upgrade
- run terraform plan

@sinkr I have a limited bandwidth, and cannot simply rewrite the core functionality of plugin for no good reason (given that exec functionality works well in tests).

_Originally posted by @alekc in https://github.com/alekc/terraform-provider-kubectl/issues/134#issuecomment-2273391134_

**Comment by alekc** [comment]
?
