### ISSUE TITLE
replace-provider gavinbunney/kubectl alekc/kubectl failed with "failed to create kubernetes rest client"

### ISSUE THREAD

**Issue by ox0** [alekc/terraform-provider-kubectl#184]
Dear @alekc ,

We encounter the very similar issue as in https://github.com/alekc/terraform-provider-kubectl/issues/134 mentioned, since it is closed, we just open a new one here.

We followed your suggestion to solve the issue like these:

`@Kartoshnikov hang on. I think I got the issue. 

Correct me if I am wrong.
You have existing infra/objects which have been created by the gavinbunney/kubectl.
You have changed provider definition from gavinbunney/kubectl to alekc/kubectl and run plan/apply where you begin to get the error.
If the above is correct, then this is whats happening. You are running a plan phase where old objects are still linked to gavinbunney/kubectl provider, but at this point of time, there is no configuration for that provider (the fact that there is alekc/kubectl is irrelevant), so terraform applies default config (localhost) and fails as consequence without even trying to execute exec-log.
Correct procedure is
make a backup of your state file
as written in https://github.com/alekc/terraform-provider-kubectl?tab=readme-ov-file#changing-providers-for-existing-resources, perform a terraform state replace-provider gavinbunney/kubectl alekc/kubectl command
run terraform init -upgrade
run terraform plan
@sinkr I have a limited bandwidth, and cannot simply rewrite the core functionality of plugin for no good reason (given that exec functionality works well in tests).

Originally posted by @alekc in #134 (comment)`

So, here is our Terraform provider part:
`  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~ > 4.0"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = "~ > 2.0"
    }

Then we did:
terraform init
terraform state replace-provider gavinbunney/kubectl alekc/kubectl
terraform init -upgrade
terraform plan
The plan run all good till this error:

data.aws_eks_cluster.busi: Refresh complete after 0s [id=busi-eks-prod]
╷
│ Error: failed to create kubernetes rest client for read of resource: Get "http://localhost/api?timeout=32s": dial tcp [::1]:80: connect: connection refused
│
│   with module.app_secrets.kubectl_manifest.external_secret,
│   on .terraform/modules/app_secrets/main.tf line 15, in resource "kubectl_manifest" "external_secret":
│   15: resource "kubectl_manifest" "external_secret" {
│
╵
Operation failed: failed running terraform plan (exit 1)`

And we tried several times, but the result is the same.

Do you see anything we missed in our attempt ?

Thank you,

Alex

**Comment by alekc** [comment]
What's your configuration for kubectl provider?

**Comment by ox0** [comment]
Hi @alekc , Really appreciate your prompt reply!
Here is the configuration:

`provider "kubectl" {
  host                   = data.aws_eks_cluster.busi.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.busi.certificate_authority[0].data)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", data.aws_eks_cluster.busi.id]
    command     = "aws"
  }
}`

Let me know if you may need anything for this, thank you!

Alex

**Comment by alekc** [comment]
The "http://localhost/api?timeout=32s" bit means that there is some kubernetes based provider in your code (kubernetes, kubectl, helm, etc) which is not configured, and its trying to reach out to localhost as default. 

Try to run `terraform providers` if it allow you to, and check the output. 

Also, setting `TF_LOG` env var to `trace` might give some very important clues as well.

**Comment by ox0** [comment]
Thank you for quick return @alekc , here is what I have with the command:

# terraform providers|gg kubectl
├── provider[registry.terraform.io/gavinbunney/kubectl] ~> 1.14.0
│   ├── provider[registry.terraform.io/gavinbunney/kubectl] >= 1.14.0
│   ├── provider[registry.terraform.io/gavinbunney/kubectl] >= 1.14.0
    provider[registry.terraform.io/gavinbunney/kubectl]

Not sure if it is helpful.  I am going to enable TF_LOG for further check if you don't see any issue on the output above.
Thank you so much.

Alex

**Comment by alekc** [comment]
Please print the full log from `terraform providers`. 

It should show if `gavinbunney/kubectl` is required by state or config. I.e. 
```
❯ terraform providers           

Providers required by configuration:
.
└── provider[registry.terraform.io/alekc/kubectl] 2.1.0

Providers required by state:

    provider[registry.terraform.io/gavinbunney/kubectl]
```

Also, from the above I am not seeing usage of `alekc/kubectl` are you sure that it's in the config?

**Comment by alekc** [comment]
Also, this is the output you should be expecting when changing providers. 
```
❯ terraform state replace-provider gavinbunney/kubectl alekc/kubectl
Terraform will perform the following actions:

  ~ Updating provider:
    - registry.terraform.io/gavinbunney/kubectl
    + registry.terraform.io/alekc/kubectl

Changing 1 resources:

  kubectl_manifest.test_wait_for

Do you want to make these changes?
Only 'yes' will be accepted to continue.

Enter a value: yes

Successfully replaced provider for 1 resources.

❯ terraform providers                                               

Providers required by configuration:
.
└── provider[registry.terraform.io/alekc/kubectl] 2.1.0

Providers required by state:

    provider[registry.terraform.io/alekc/kubectl]

```

**Comment by ox0** [comment]
Hi @alekc , Sorry for delayed response.

We followed your suggestion and replaced **all** module which use gavinbunney/kubectl with alekc/kubectl.  This took a while since many places need to be updated.

And we did **solve** the problem !!!

Thank you so much for your quick response and tips which lead us to the resolution.
We do appreciate your sincere support.

Alex with the team

**Comment by ox0** [comment]
Thank you @alekc again, and I am closing this issue now.

Alex
