### ISSUE TITLE
wait_for block with conditions doesn't work for updates

### ISSUE THREAD

**Issue by bojandjukic1** [alekc/terraform-provider-kubectl#186]
Feel free to close if this is the intended behaviour however I noticed that when specifying a `wait_for` block with  a condition, the wait for is only respected during the apply of the resource, not during updates. A work around seems to be to specify `force_new` however this is not ideal. 

The use case where this is relevant is when deploying an operator custom resource manifest and setting dependencies on the custom resource manifest. Behind the scenes, the operator can control deployments and other resources and the calling code doesn't need to set up dependencies on all the managed resources but rather just a dependency on the operator manifest. This only works reliably if the `kubectl_manifest` resource `wait_for` works for applies AND updates, i.e. say I update an operator custom resource field and it requires a restart of the workload to take effect, the current behaviour seems to be that wait_for is ignored when the custom resource is updated, resulting in the modification completing instantly, even though the condition on the custom resource changes to Ready.

It could also be the case that the wait_for does work for updates however a race condition causes the provider to consider the condition field, e.g. `type: Ready, status: True` as being met before the field is transitioned by the operator as it detects changes.

**Comment by stevehipwell** [comment]
@bojandjukic1 which version of the provider are you using?

**Comment by bojandjukic1** [comment]
@stevehipwell 2.1.2

**Comment by stevehipwell** [comment]
@bojandjukic1 do you have an example of this issue that can be reproduced?

**Comment by stevehipwell** [comment]
@bojandjukic1 I've added tests to simulate an update in #193 and they work as expected. I think we'd need to have more context from you to figure out why they aren't working.

**Comment by bojandjukic1** [comment]
Thanks @stevehipwell , sounds like it's probably a race condition then between the kubectl provider updating the resource and the field being waited on not immediately being changed by the operator which watches the manifest which leads to an immediate modifications complicate rather than the intended wait. I'll see if I can provide a reproducible example but at any rate it sounds like the kubectl side of things is working as expected
