### ISSUE TITLE
upgrade client-go?

### ISSUE THREAD

**Issue by yongzhang** [alekc/terraform-provider-kubectl#20]
Hi,

Would it be possible to upgrade client-go to a higher version? Thanks.

**Comment by alekc** [comment]
Sure, on it.

**Comment by alekc** [comment]
@yongzhang client-go and bunch of other dependencies (i.e. api machinery etc) has been released in [rc1](https://github.com/alekc/terraform-provider-kubectl/releases/tag/v2.0.3-rc1)

```
terraform {
  required_providers {
    kubectl = {
      source = "alekc/kubectl"
      version = "2.0.3-rc1"
    }
  }
}
```

Feel free to test it as well, and I expect it to be released in full at the end of the week give or take.

**Comment by yongzhang** [comment]
> @yongzhang client-go and bunch of other dependencies (i.e. api machinery etc) has been released in [rc1](https://github.com/alekc/terraform-provider-kubectl/releases/tag/v2.0.3-rc1)
> 
> ```
> terraform {
>   required_providers {
>     kubectl = {
>       source = "alekc/kubectl"
>       version = "2.0.3-rc1"
>     }
>   }
> }
> ```
> 
> Feel free to test it as well, and I expect it to be released in full at the end of the week give or take.

Cool! Thank you!

**Comment by yongzhang** [comment]
It works on my 1.26 cluster, no issues so far.
