### ISSUE TITLE
Using 'templatefile' to pass TF vars into manifests .yaml 

### ISSUE THREAD

**Issue by mht-incom** [alekc/terraform-provider-kubectl#61]
Is it possible to be able to use templatefile to pass vars, a bit like shown below:

resource "kubectl_manifest" "directory-yaml" {
  for_each  = data.kubectl_path_documents.manifests-directory-yaml.manifests
  yaml_body = templatefile("./manifests/${each.key}.yaml", {
    net = var.net
  })
}

or is there any other prefered way to do this?

simply setting up manifests with the yaml_body, gives the option to pass vars, but it also seems extremely inconsistent, since I'll get errors on future applies, that TF can't determine if the resource is created or not in the cluster.

**Comment by alekc** [comment]
@mht-incom Uhm you are combining several things in here, thats why it's failing probably. 

If I got right what you are trying to achieve, it should be something like this for a single manifest:
```hcl
resource "kubectl_manifest" "directory-yaml" {
  yaml_body = templatefile("./manifests/file.yaml", {
    net = var.net
  })
}
```
or in case of many files
```hcl
resource "kubectl_manifest" "directory-yaml" {
 for_each = fileset(path.module, "files/*")
  yaml_body = templatefile("./manifests/${each.key}.yaml", {
    net = var.net
  })
}
```

While using templatefile, 1 file must contain only 1 manifest

**Comment by mht-incom** [comment]
Hey again Alexander,

You're completely right, I was overcomplicating it I guess.

I'll try out this method & see if that'll smooth it out 👍 😄 

Thanks a lot!
