### ISSUE TITLE
Using an outputted "dynamic" kubeconfig.yml file as config_path

### ISSUE THREAD

**Issue by mht-incom** [alekc/terraform-provider-kubectl#62]
Hey again,

Sorry for the repeated issues.

In a use case where your script creates a cluster & outputs the kubeconfig file into the module-path, the script always seems to file whenever it reaches the kubectl stage, since we're using the config path i.e.

provider "kubectl" {
  config_path    = "${path.module}/../../kubeconfig.yml"
  load_config_file = true
  insecure = true

}

It seems like Terraform preloads the kubeconfig, so if there's an existing kubeconfig from a previous deleted cluster, it'll load the old one, before It's replaced by the new one outputted a few seconds into the script.

Simply running the script again after it fails, will let the script continue, since it seems that it can then proceed with the newly generated kubeconfig, actually matching the cluster.

Is there anyway to remediate this as of right now, for on-premise clusters where using the config_path seems like the only valid option?

**Comment by alekc** [comment]
Try to have a look at https://github.com/alekc/terraform-provider-kubectl/issues/18 and see if that can help you.
