### ISSUE TITLE
make timeout configurable

### ISSUE THREAD

**Issue by vrabbi** [alekc/terraform-provider-kubectl#7]
can you add a timeout field for apply of a kubectl_manifest? i think its currently hardcoded and certail resources we are dealing with when waiting for a condition is exceeding this timeout making it not work

**Comment by alekc** [comment]
mm, I will have a look. It might be set up on the terraform level and not on the provider.

**Comment by stevehipwell** [comment]
Terraform has the concept of timeouts built in, but you should be able to either override or augment this through the resource (or data source) API as the Helm provider does.

**Comment by alekc** [comment]
@vrabbi this is an old one, but could you try with 
```
resource "kubectl_manifest" "test_wait_for" {
  timeouts {
    create = "20s"
  }
  yaml_body = <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: test-wait-for
EOF

  wait_for {
    field {
      key = "status.phase"
      value = "Active"
    }
  }
}
```
