### ISSUE TITLE
Support where clause in wait_for fields

### ISSUE THREAD

**Issue by jorgemoralespou** [alekc/terraform-provider-kubectl#72]
Currently, wait_for fields uses `https://github.com/thedevsaddam/gojsonq` for querying the resulting json. I have a case where I need to do a `where` clause in an array that in regular json query would be something like [?(@.type=="value")] so that the item with `type: value` would be selected and then another field be retrieved. Currently this is not possible.

e.g. doc:
```
{
    "apiVersion": "v1,
    "kind": "MyObject",
    "metadata": {
        "name": "sample",
    },
    "spec": {
       ...
    },
    "status": {
        "conditions": [
            {
                "status": "True",
                "type": "ReconcileSucceeded"
            }
        ],
        ...
    }
}
```

My query would be something like:
```
  wait_for {
    field {
      key   = "status.conditions.[?(@.type=='ReconcileSucceeded')].status"
      value = "True"
    }
  }
```

I could replace all that with a zero index, but that would be error prone, as I need both values to be equal. I could implement 2 conditions, but that is not really nice.

**Comment by alekc** [comment]
That feels way overcomplicated for terraform tbh... The idea for wait_for was to provide a minimum support for a waiting period within terraform itself, such a complex logic might be better served by a dedicated step in a cicd pipeline.

**Comment by jorgemoralespou** [comment]
Ended up doing a double condition:
```
  wait_for {
    field {
      key   = "status.conditions.[0].type"
      value = "ReconcileSucceeded"
    }
    field {
      key   = "status.conditions.[0].status"
      value = "True"
    }
  }
```

Hoping that element 0 is what should be
