### ISSUE TITLE
Support `proxy_url`

### ISSUE THREAD

**Issue by mathe-matician** [alekc/terraform-provider-kubectl#75]
The original repo's `master` had changes to support `proxy_url`: https://github.com/gavinbunney/terraform-provider-kubectl/blob/8e4af599e17a3d8d73defd5cff392bbe23cc9c6f/kubernetes/provider.go#L124-L129

Since this is the now active repo, it would be great to implement support for `proxy_url` here.

**Comment by thpham** [comment]
Would be very cool to move forward with that. @alekc , If I take some time to propose a PR, would you be ok to review, merge and do a new release ?

**Comment by alekc** [comment]
Also, since you've required this functionality please confirm that it's working properly. I am a bit limited in testing it due to the nature of the requirement (don't have a proper proxy with certs or socks set up).

**Comment by thpham** [comment]
This looks ok for me for now, because I never had the chance to test the original feature as it was in the main branch but not in the last release. But I will probably be able to test again over Xmas time.

**Comment by alekc** [comment]
Released in 2.0.4
