### ISSUE TITLE
Server side apply - port fixes

### ISSUE THREAD

**Issue by joaocc** [alekc/terraform-provider-kubectl#79]
Hi
We have tried moving to server-side apply, but we kept getting errors like the ones reported in https://github.com/gavinbunney/terraform-provider-kubectl/issues/139 when creating ExternalSecrets.
Apparently there is a fix here https://github.com/gavinbunney/terraform-provider-kubectl/issues/139#issuecomment-1077049925
but doesn't seem to have been released.
Would it be possible to add this to your fork?
Thanks

**Comment by alekc** [comment]
I will have a look. Could you provide an example triggering the error?

**Comment by joaocc** [comment]
Creating any ExternalSecret triggered this at second execution (where there should be no changes) (I had to move on from this, disabling `server_side_apply`).
```
my-ns/my-ext-secret-name  failed to run apply: Apply failed with 1 conflict: conflict with "HashiCorp" using external-secrets.io/v1beta1: .spec.data
```

However, I think this is intentional on the part of external-secrets.
I am however curious why `kubernetes_manifest` was not raising any issues as it mentions it uses server-side-apply as well (I have been converting from `kubernetes_manifest` to `kubectl_manifest` due to better diff and the fact that sometimes they remove recreate resources instead of updating).

For reference, they seem to change some fields (https://external-secrets.io/v0.8.1/guides/ownership-deletion-policy/#merge).
Also more relevant info on this here https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts

**Comment by joaocc** [comment]
Hi. This also seems to occur on ClusterIssuer resources (of cert-man, API cert-manager.io/v1).
The original creation went OK, but then added annotations, and got this:
```
  # module.my_issuer[0].kubectl_manifest.this_issuer[0] will be updated in-place
  ~ resource "kubectl_manifest" "this_issuer" {
        id                      = "/apis/cert-manager.io/v1/clusterissuers/my-le-cert-issuer"
        name                    = "my-le-cert-issuer"
      ~ yaml_body               = (sensitive value)
      ~ yaml_body_parsed        = <<-EOT
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
          -   annotations: {}
          +   annotations:
          +     new-annotation: new-annotation-value
              labels: null
              name: my-le-cert-issuer
            spec:
              acme:
                email: something@email.here
                privateKeySecretRef:
                  name: my-le-cert-issuer
                server: https://acme-v02.api.letsencrypt.org/directory
                solvers:
                  ......
        EOT
        # (14 unchanged attributes hidden)
    }
```
```
Plan: 1 to add, 3 to change, 0 to destroy.
module.my_issuer[0].kubectl_manifest.this_issuer[0]: Modifying... [id=/apis/cert-manager.io/v1/clusterissuers/my-le-cert-issuer]

│ Error: my-le-cert-issuer failed to run apply: Apply failed with 1 conflict: conflict with "HashiCorp" using cert-manager.io/v1: .spec.acme.solvers
│ Please review the fields above--they currently have other managers. Here
│ are the ways you can resolve this warning:
│ * If you intend to manage all of these fields, please re-run the apply
│   command with the `--force-conflicts` flag.
│ * If you do not intend to manage all of the fields, please edit your
│   manifest to remove references to the fields that should keep their
│   current managers.
│ * You may co-own fields by updating your manifest to match the existing
│   value; in this case, you'll become the manager if the other manager(s)
│   stop managing the field (remove it from their configuration).
│ See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
│ 
│   with module.my_issuer[0].kubectl_manifest.this_issuer[0],
│   on ../main.tf line 168, in resource "kubectl_manifest" "this_issuer":
│  168: resource "kubectl_manifest" "this_issuer" {
```

As before, my workaround is to disable `server_side_apply`, but didn't seem to happen with `kubernetes_manifest`.

**Comment by alekc** [comment]
@joaocc Hi, apologies, due to my schedule I just got to work on this right now. 

After checking the source code, it looks like there is a `force_conflicts` property already (https://registry.terraform.io/providers/alekc/kubectl/latest/docs/resources/kubectl_manifest#force_conflicts) which should cover this issue. 

checked with applying 
```hcl
resource "kubectl_manifest" "xxx" {
  server_side_apply = true
  yaml_body = <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  annotations:
    xx: "112"
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
EOF
}
```
Changing manually the property of the annotation, running the apply again (and getting the error). 

After adding force_conflicts to the yaml, it worked
```hcl
resource "kubectl_manifest" "xxx" {
  //language=yaml
  server_side_apply = true
  force_conflicts = true
  yaml_body = <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  annotations:
    xx: "112"
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
EOF
}
```

Could you please check if that solves your issue?

**Comment by joaocc** [comment]
Thx for the update. 
In this case, I tried not to change anything that could risk the integrity of the data, and the documentation was not clear (for me) on what the implications would do. 
My understanding is that the owner field is a mechanism explicitly created to make sure that different tools don't get in each others way (in this case, external-secrets and cert-manager), so overriding them is a risk we would prefer not to take, or taking only when absolutely sure of the implications, as the downfall of having to recreate some of the in production is not trivial.
I would like to get a better understanding of what is the effect of using the "force-conflict", and why that is needed for kubectl_manifest (as kubernetes_manifest also uses ssa but doesn't seem to cause this).
In our case, we moved no disable SSA, which solved the issue.
Do you know why kubectl_manifest seems to be more sensitive to this than kubernetes_manifest?
Thanks

**Comment by alekc** [comment]
@joaocc from the kubernetes documentation (https://kubernetes.io/docs/reference/using-api/server-side-apply/) 

> A Server-Side Apply patch request requires the client to provide its identity as a [field manager](https://kubernetes.io/docs/reference/using-api/server-side-apply/#managers). When using Server-Side Apply, trying to change a field that is controlled by a different manager results in a rejected request unless the client forces an override. For details of overrides, see [Conflicts](https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts).

And 
> Conflicts
A conflict is a special status error that occurs when an Apply operation tries to change a field that another manager also claims to manage. This prevents an applier from unintentionally overwriting the value set by another user. When this occurs, the applier has 3 options to resolve the conflicts:

> Overwrite value, become sole manager: If overwriting the value was intentional (or if the applier is an automated process like a controller) the applier should set the force query parameter to true (for kubectl apply, you use the --force-conflicts command line parameter), and make the request again. This forces the operation to succeed, changes the value of the field, and removes the field from all other managers' entries in managedFields.
> 
> Don't overwrite value, give up management claim: If the applier doesn't care about the value of the field any more, the applier can remove it from their local model of the resource, and make a new request with that particular field omitted. This leaves the value unchanged, and causes the field to be removed from the applier's entry in managedFields.
> 
> Don't overwrite value, become shared manager: If the applier still cares about the value of a field, but doesn't want to overwrite it, they can change the value of that field in their local model of the resource so as to match the value of the object on the server, and then make a new request that takes into account that local update. Doing so leaves the value unchanged, and causes that field's management to be shared by the applier along with all other field managers that already claimed to manage it.
> 

So, if you are using the serverside apply to change a property already claimed by another fieldmanager you should always receive a conflict regardless of the client type. If you are not receiving it, probably it's using `force` flag already

**Comment by alekc** [comment]
Closing this off for now. Feel free to reopen if needed.

**Comment by joaocc** [comment]
Hi. Thanks for the clarification.
However, we are simply creating a new resource, which requires us to specify the fields of the resource. Any update to the manifest fields has triggered this.
We never had any kind of issues with either `kubernetes_manifest` (which uses server_side_apply) or `flux2` (which we used before).
Digging a bit, it seems `flux2` does indeed use `force_ownership` (https://github.com/fluxcd/flux2/discussions/2266#discussioncomment-1927373)
